"""Create clients table and sales table.

Revision ID: 05ce8edda5d8
Revises: ed67462aaecf
Create Date: 2024-07-05 11:31:36.307675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05ce8edda5d8'
down_revision: Union[str, None] = 'ed67462aaecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客戶編號'),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='客戶名稱'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='住址'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False, comment='訂單編號'),
    sa.Column('order_date', sa.String(length=255), nullable=False, comment='訂單日期'),
    sa.Column('shipping_date', sa.String(length=255), nullable=False, comment='出貨日期'),
    sa.Column('delivery_method', sa.String(length=255), nullable=False, comment='配送方式'),
    sa.Column('city', sa.String(length=255), nullable=False, comment='城市'),
    sa.Column('country', sa.String(length=255), nullable=False, comment='國家'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='產品名稱'),
    sa.Column('product_type', sa.String(length=255), nullable=False, comment='產品類別'),
    sa.Column('sales_number', sa.Integer(), nullable=False, comment='銷售數量'),
    sa.Column('sales_amount', sa.Integer(), nullable=False, comment='銷售金額'),
    sa.Column('profit', sa.Integer(), nullable=False, comment='利潤'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    op.drop_table('example_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('sales')
    op.drop_table('clients')
    # ### end Alembic commands ###
